import { useEffect, useRef, type ReactNode } from 'react'
import { LoaderCircle, RefreshCw } from 'lucide-react'
import { localDateString, type DailyBriefNote } from '@local-brain/core'
import { Alert } from '../components/alert'
import { Button } from '../components/button'
import { ChatMarkdown } from '../components/chat/chat-markdown'
import { PageHead } from '../components/page-head'
import { Section } from '../components/section'
import { EmptyState } from '../components/empty-state'
import { Loading } from '../components/loading'
import { SuggestionsList } from '../components/suggestions-list'
import { metaText, sectionLabel } from '../lib/ui'
import { cn } from '../lib/utils'
import { useRouter } from '../routing/router'
import {
  useDailyBriefNote,
  useGenerateDailyBrief,
  useInteractions,
  useModelSettings,
  useProjects,
  useSelf,
  useTasks,
} from '../lib/queries'

/** The Today brief: a generated-operating-brief shell over real queries. */
export function TodaySurface(): ReactNode {
  const { navigate } = useRouter()
  const today = localDateString()
  const autoGenerateDate = useRef<string | null>(null)
  const self = useSelf()
  const openTasks = useTasks({ status: 'open', limit: 6 })
  const interactions = useInteractions(5)
  const projects = useProjects()
  const modelSettings = useModelSettings()
  const dailyBrief = useDailyBriefNote(today)
  const generateBrief = useGenerateDailyBrief(today)

  const name = self.data?.preferredName ?? self.data?.fullName ?? 'there'
  const providersReady = Boolean(modelSettings.data && modelSettings.data.providers.length > 0)

  useEffect(() => {
    if (
      dailyBrief.isPending ||
      dailyBrief.isFetching ||
      dailyBrief.isError ||
      dailyBrief.data !== null ||
      !providersReady ||
      generateBrief.isPending ||
      autoGenerateDate.current === today
    ) {
      return
    }
    autoGenerateDate.current = today
    generateBrief.mutate()
  }, [
    dailyBrief.data,
    dailyBrief.isError,
    dailyBrief.isFetching,
    dailyBrief.isPending,
    generateBrief,
    providersReady,
    today,
  ])

  return (
    <div className="mx-auto flex max-w-3xl flex-col gap-7">
      <PageHead eyebrow={todayLabel()} title={`Good to see you, ${name}`} />

      <DailyBriefPanel
        note={dailyBrief.data ?? null}
        loading={dailyBrief.isPending || (dailyBrief.isFetching && dailyBrief.data == null)}
        generating={generateBrief.isPending}
        error={generateBrief.error}
        providersReady={providersReady}
        settingsLoading={modelSettings.isPending}
        onGenerate={() => generateBrief.mutate()}
        onConfigure={() => navigate({ kind: 'settings', section: 'ai-providers' })}
      />

      <Section title="Open tasks">
        {openTasks.data && openTasks.data.length > 0 ? (
          <ul className="flex flex-col gap-1">
            {openTasks.data.map((task) => (
              <li key={task.id}>
                <button
                  type="button"
                  onClick={() => navigate({ kind: 'task', id: task.id })}
                  className="flex w-full items-center justify-between rounded-md px-2.5 py-1.5 text-left text-sm hover:bg-secondary/60"
                >
                  <span className="text-foreground">{task.title}</span>
                  {task.dueAt ? (
                    <span className="font-mono text-[11px] text-muted-foreground">
                      {task.dueAt.slice(0, 10)}
                    </span>
                  ) : null}
                </button>
              </li>
            ))}
          </ul>
        ) : (
          <EmptyState title="No open tasks" hint="Enjoy the calm." />
        )}
      </Section>

      <SuggestionsList />

      <Section title="Recent interactions">
        {interactions.data && interactions.data.length > 0 ? (
          <ul className="flex flex-col gap-1">
            {interactions.data.map((interaction) => (
              <li key={interaction.id}>
                <button
                  type="button"
                  onClick={() => navigate({ kind: 'interaction', id: interaction.id })}
                  className="flex w-full items-center justify-between rounded-md px-2.5 py-1.5 text-left text-sm hover:bg-secondary/60"
                >
                  <span className="text-foreground">{interaction.title ?? interaction.kind}</span>
                  {interaction.occurredAt ? (
                    <span className="font-mono text-[11px] text-muted-foreground">
                      {interaction.occurredAt.slice(0, 10)}
                    </span>
                  ) : null}
                </button>
              </li>
            ))}
          </ul>
        ) : (
          <EmptyState title="No interactions yet" />
        )}
      </Section>

      <Section title="Active projects">
        {projects.data && projects.data.length > 0 ? (
          <ul className="flex flex-col gap-1">
            {projects.data.map((project) => (
              <li key={project.id}>
                <button
                  type="button"
                  onClick={() => navigate({ kind: 'project', id: project.id })}
                  className="flex w-full items-center justify-between rounded-md px-2.5 py-1.5 text-left text-sm hover:bg-secondary/60"
                >
                  <span className="text-foreground">{project.name}</span>
                  <span className="font-mono text-[11px] text-muted-foreground">
                    {project.status}
                  </span>
                </button>
              </li>
            ))}
          </ul>
        ) : (
          <EmptyState title="No active projects" />
        )}
      </Section>
    </div>
  )
}

function DailyBriefPanel({
  note,
  loading,
  generating,
  error,
  providersReady,
  settingsLoading,
  onGenerate,
  onConfigure,
}: {
  note: DailyBriefNote | null
  loading: boolean
  generating: boolean
  error: Error | null
  providersReady: boolean
  settingsLoading: boolean
  onGenerate: () => void
  onConfigure: () => void
}): ReactNode {
  const hasBrief = note !== null
  const disabled = loading || generating || settingsLoading
  const action = providersReady ? (
    <Button size="sm" variant={hasBrief ? 'outline' : 'primary'} disabled={disabled} onClick={onGenerate}>
      {generating ? <LoaderCircle aria-hidden className="size-3.5 animate-spin" /> : null}
      {!generating && hasBrief ? <RefreshCw aria-hidden className="size-3.5" /> : null}
      {generating ? 'Generating' : hasBrief ? 'Regenerate' : 'Generate'}
    </Button>
  ) : (
    <Button size="sm" variant="primary" disabled={settingsLoading} onClick={onConfigure}>
      Add provider
    </Button>
  )

  return (
    <section className="flex flex-col gap-2">
      <div className="flex items-end justify-between gap-3">
        <div>
          <h2 className={sectionLabel}>Daily brief</h2>
          {note?.generatedAt ? (
            <p className={cn(metaText, 'mt-1')}>Generated {formatGeneratedAt(note.generatedAt)}</p>
          ) : null}
        </div>
        {action}
      </div>

      <div className="rounded-lg border border-border bg-card px-4 py-3.5">
        {error ? (
          <Alert variant="error">
            {error.message}
          </Alert>
        ) : null}

        {generating && !hasBrief ? (
          <div
            role="status"
            aria-label="Generating daily brief"
            className="flex items-center gap-2 text-sm text-muted-foreground"
          >
            <LoaderCircle aria-hidden className="size-4 animate-spin" />
            <span>Generating brief...</span>
          </div>
        ) : loading ? (
          <Loading />
        ) : hasBrief ? (
          <ChatMarkdown text={note.content} />
        ) : (
          <p className="text-sm leading-6 text-muted-foreground">
            Generate a grounded brief from today&apos;s tasks, active projects, and recent
            interactions.
          </p>
        )}
      </div>
    </section>
  )
}

function formatGeneratedAt(value: string): string {
  return new Date(value).toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })
}

function todayLabel(): string {
  return new Date().toLocaleDateString(undefined, {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  })
}
