import { useEffect, useRef, type ReactNode } from 'react'
import { LoaderCircle, RefreshCw } from 'lucide-react'
import { localDateString, type DailyBriefNote } from '@local-brain/core'
import { Alert } from '../components/alert'
import { Button } from '../components/button'
import { ChatMarkdown } from '../components/chat/chat-markdown'
import { PageHead } from '../components/page-head'
import { QueryError } from '../components/query-error'
import { Section } from '../components/section'
import { EmptyState } from '../components/empty-state'
import { Loading } from '../components/loading'
import { SuggestionsList } from '../components/suggestions-list'
import {
  TaskCompletionFeedback,
  TaskCompletionFeedbackProvider,
} from '../components/task-completion-feedback'
import { TaskList } from '../components/task-list'
import { metaText, sectionLabel } from '../lib/ui'
import { cn } from '../lib/utils'
import { useRouter } from '../routing/router'
import {
  useDailyBriefNote,
  useGenerateDailyBrief,
  useInteractions,
  useModelSettings,
  useSelf,
  useTasks,
} from '../lib/queries'
import { groupTodayTasks } from './today-task-groups'

/** The Today brief: a generated-operating-brief shell over real queries. */
export function TodaySurface(): ReactNode {
  const { navigate } = useRouter()
  const today = localDateString()
  const autoGenerateDate = useRef<string | null>(null)
  const self = useSelf()
  const tasks = useTasks()
  const interactions = useInteractions(5)
  const modelSettings = useModelSettings()
  const dailyBrief = useDailyBriefNote(today)
  const generateBrief = useGenerateDailyBrief(today)
  const taskGroups = groupTodayTasks(tasks.data ?? [], today)
  const hasTasks = Object.values(taskGroups).some((group) => group.length > 0)

  const name = self.data?.preferredName ?? self.data?.fullName ?? 'there'
  const providersReady = Boolean(modelSettings.data && modelSettings.data.providers.length > 0)

  useEffect(() => {
    if (
      dailyBrief.isPending ||
      dailyBrief.isFetching ||
      dailyBrief.isError ||
      dailyBrief.data !== null ||
      !providersReady ||
      generateBrief.isPending ||
      autoGenerateDate.current === today
    ) {
      return
    }
    autoGenerateDate.current = today
    generateBrief.mutate()
  }, [
    dailyBrief.data,
    dailyBrief.isError,
    dailyBrief.isFetching,
    dailyBrief.isPending,
    generateBrief,
    providersReady,
    today,
  ])

  return (
    <TaskCompletionFeedbackProvider>
      <div className="mx-auto flex max-w-3xl flex-col gap-7">
        <PageHead
          eyebrow={todayLabel()}
          title={`Good to see you, ${name}`}
          actions={(
            <Button size="sm" variant="ghost" onClick={() => navigate({ kind: 'tasks' })}>
              View tasks
            </Button>
          )}
        />

        <DailyBriefPanel
          note={dailyBrief.data ?? null}
          loading={dailyBrief.isPending || (dailyBrief.isFetching && dailyBrief.data == null)}
          generating={generateBrief.isPending}
          error={generateBrief.error}
          loadError={dailyBrief.error}
          providersReady={providersReady}
          settingsLoading={modelSettings.isPending}
          onGenerate={() => generateBrief.mutate()}
          onRetry={() => void dailyBrief.refetch()}
          onConfigure={() => navigate({ kind: 'settings', section: 'ai-providers' })}
        />

        <TaskCompletionFeedback />

        {tasks.isError && !tasks.data ? (
          <QueryError
            title="Could not load tasks"
            error={tasks.error}
            onRetry={() => void tasks.refetch()}
          />
        ) : tasks.isPending ? (
          <Loading />
        ) : (
          <>
            {tasks.isError ? (
              <QueryError
                title="Could not refresh tasks"
                error={tasks.error}
                onRetry={() => void tasks.refetch()}
              />
            ) : null}
            {hasTasks ? (
              <>
                {taskGroups.due.length > 0 ? (
                  <Section title="Due now"><TaskList tasks={taskGroups.due.slice(0, 6)} /></Section>
                ) : null}
                {taskGroups.scheduled.length > 0 ? (
                  <Section title="Scheduled"><TaskList tasks={taskGroups.scheduled.slice(0, 6)} /></Section>
                ) : null}
                {taskGroups.waiting.length > 0 ? (
                  <Section title="Waiting"><TaskList tasks={taskGroups.waiting.slice(0, 6)} /></Section>
                ) : null}
                {taskGroups.open.length > 0 ? (
                  <Section title="Open tasks"><TaskList tasks={taskGroups.open.slice(0, 6)} /></Section>
                ) : null}
              </>
            ) : (
              <Section title="Tasks">
                <EmptyState title="No active tasks" hint="Enjoy the calm." />
              </Section>
            )}
          </>
        )}

        <SuggestionsList />

        <Section title="Recent interactions">
          {interactions.isError && !interactions.data ? (
            <QueryError
              title="Could not load recent interactions"
              error={interactions.error}
              onRetry={() => void interactions.refetch()}
            />
          ) : interactions.isPending ? (
            <Loading />
          ) : (
            <>
              {interactions.isError ? (
                <QueryError
                  title="Could not refresh recent interactions"
                  error={interactions.error}
                  onRetry={() => void interactions.refetch()}
                />
              ) : null}
              {interactions.data && interactions.data.length > 0 ? (
                <ul className="flex flex-col gap-1">
                  {interactions.data.map((interaction) => (
                    <li key={interaction.id}>
                      <button
                        type="button"
                        onClick={() => navigate({ kind: 'interaction', id: interaction.id })}
                        className="flex w-full items-center justify-between rounded-md px-2.5 py-1.5 text-left text-sm hover:bg-secondary/60"
                      >
                        <span className="text-foreground">{interaction.title ?? interaction.kind}</span>
                        {interaction.occurredAt ? (
                          <span className="font-mono text-[11px] text-muted-foreground">
                            {interaction.occurredAt.slice(0, 10)}
                          </span>
                        ) : null}
                      </button>
                    </li>
                  ))}
                </ul>
              ) : (
                <EmptyState title="No interactions yet" />
              )}
            </>
          )}
        </Section>
      </div>
    </TaskCompletionFeedbackProvider>
  )
}

function DailyBriefPanel({
  note,
  loading,
  generating,
  error,
  loadError,
  providersReady,
  settingsLoading,
  onGenerate,
  onRetry,
  onConfigure,
}: {
  note: DailyBriefNote | null
  loading: boolean
  generating: boolean
  error: Error | null
  loadError: Error | null
  providersReady: boolean
  settingsLoading: boolean
  onGenerate: () => void
  onRetry: () => void
  onConfigure: () => void
}): ReactNode {
  const hasBrief = note !== null
  const disabled = loading || generating || settingsLoading
  const headerAction = hasBrief ? (
    providersReady ? (
      <Button
        size="sm"
        variant="ghost"
        disabled={disabled}
        onClick={onGenerate}
        className="h-auto px-0 underline-offset-4 hover:bg-transparent hover:underline"
      >
        {generating ? <LoaderCircle aria-hidden className="size-3.5 animate-spin" /> : null}
        {!generating ? <RefreshCw aria-hidden className="size-3" /> : null}
        {generating ? 'Generating' : 'Regenerate'}
      </Button>
    ) : (
      <Button size="sm" variant="primary" disabled={settingsLoading} onClick={onConfigure}>
        Add provider
      </Button>
    )
  ) : null
  const emptyAction = providersReady ? (
    <Button
      size="sm"
      variant="primary"
      disabled={disabled}
      onClick={onGenerate}
    >
      {generating ? <LoaderCircle aria-hidden className="size-3.5 animate-spin" /> : null}
      {generating ? 'Generating' : 'Generate'}
    </Button>
  ) : (
    <Button size="sm" variant="primary" disabled={settingsLoading} onClick={onConfigure}>
      Add provider
    </Button>
  )

  return (
    <section className="flex flex-col gap-2">
      <div className="flex items-end justify-between gap-3">
        <div>
          <h2 className={sectionLabel}>Daily brief</h2>
        </div>
        {headerAction}
      </div>

      <div
        className={cn(
          'rounded-lg border border-border bg-card px-4 py-3.5',
          !hasBrief && 'flex min-h-36 flex-col items-center justify-center gap-3 text-center',
        )}
      >
        {loadError ? (
          <Alert variant="error">
            Could not load the daily brief.
            <Button className="ml-2" size="sm" variant="outline" onClick={onRetry}>
              Retry
            </Button>
          </Alert>
        ) : error ? (
          <Alert variant="error">
            {error.message}
          </Alert>
        ) : null}

        {loadError && !hasBrief ? null : generating && !hasBrief ? (
          <div
            role="status"
            aria-label="Generating daily brief"
            className="flex items-center gap-2 text-sm text-muted-foreground"
          >
            <LoaderCircle aria-hidden className="size-4 animate-spin" />
            <span>Generating brief...</span>
          </div>
        ) : loading ? (
          <Loading />
        ) : hasBrief ? (
          <ChatMarkdown text={note.content} />
        ) : (
          <>
            <p className="max-w-md text-sm leading-6 text-muted-foreground">
              Generate a grounded brief from recent email context, interactions, waiting items,
              tasks, and active projects.
            </p>
            {emptyAction}
          </>
        )}
      </div>

      {note?.generatedAt ? (
        <p className={cn(metaText, '-mt-0.5 text-right text-[10px]')}>Generated {formatGeneratedAt(note.generatedAt)}</p>
      ) : null}
    </section>
  )
}

function formatGeneratedAt(value: string): string {
  return new Date(value).toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })
}

function todayLabel(): string {
  return new Date().toLocaleDateString(undefined, {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
  })
}
